version: "3.3"
services:
  db:
    &db
    image: postgres
    volumes:
      - ./data/db:/var/lib/postgresql/data
    environment:
      - POSTGRES_NAME=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
  web:
    &web
    build: .
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - ./composeexample:/code
    ports:
      - "8000:8000"
    environment:
      - POSTGRES_NAME=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    depends_on:
      - db

  web_local:
    << : *web
    ports:
      - "8010:8000"
    environment:
      - POSTGRES_NAME=postgres_local
      - POSTGRES_USER=postgres_local
      - POSTGRES_PASSWORD=postgres_local
    depends_on:
      - db_local

  db_local:
    << : *db
    volumes:
      - ./data/db_local:/var/lib/postgresql/data
    environment:
      - POSTGRES_NAME=postgres_local
      - POSTGRES_USER=postgres_local
      - POSTGRES_PASSWORD=postgres_local