# Generated by Django 3.2.12 on 2022-03-01 16:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parsing', '0001_add_network'),
    ]

    operations = [
        migrations.AddField(
            model_name='network',
            name='description',
            field=models.CharField(default='', max_length=512, verbose_name='Анонс'),
        ),
    ]
