# Generated by Django 3.2.12 on 2022-03-01 16:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parsing', '0002_network_description'),
    ]

    operations = [
        migrations.CreateModel(
            name='About',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('verbose_description', models.CharField(max_length=512, verbose_name='\xa0About')),
            ],
        ),
        migrations.AlterField(
            model_name='network',
            name='description',
            field=models.CharField(blank=True, default='', max_length=512, verbose_name='Анонс'),
        ),
    ]
