# Generated by Django 3.2.12 on 2022-03-01 16:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('parsing', '0003_auto_20220301_1628'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='about',
            options={'verbose_name': 'О нас'},
        ),
    ]
