# Generated by Django 3.2.12 on 2022-03-01 16:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('parsing', '0004_alter_about_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='about',
            options={'verbose_name': 'О нас', 'verbose_name_plural': 'О нас'},
        ),
    ]
